[workspace]
members = ["frontend", "backend"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "AGPL-3.0"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
pedantic = { level = "deny", priority = -1 }
must_use_candidate = "allow"
too_many_lines = "allow"

[workspace.lints.rust]
unsafe_code = "forbid"
