name = "cadiotheka"
main = "build/worker/shim.mjs"
compatibility_date = "2026-07-15"
upload_source_maps = true

[[d1_databases]]
binding = "DB"
database_name = "cadiotheka"

[[kv_namespaces]]
binding = "AUTH"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "843579668967"

  [ratelimits.simple]
  limit = 30
  period = 60

[[r2_buckets]]
binding = "PROJECT_ASSETS"

[secrets]
required = [
    "SESSION_SECRET",
    "TURNSTILE_SECRET",
    "GITHUB_CLIENT_ID",
    "GITHUB_CLIENT_SECRET",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
]

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
