name = "cadiotheka-backend"
main = "build/worker/shim.mjs"
compatibility_date = "2026-07-15"

[[d1_databases]]
binding = "DB"
database_name = "cadiotheka"
database_id = "c4694439-e7f4-48e0-9e2a-a7e431a8fbce"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
