mod app;

// Layout sections
pub mod components {
    pub mod sections {
        pub mod footer;
        pub mod header;
        pub mod projects;
    }

    pub mod cards {
        pub mod project_card;
    }

    pub mod effects {
        pub mod section_fade;
    }

    pub mod ui {
        pub mod corner_frame;
        pub mod markdown;
        pub mod modals {
            pub mod profile_modal;
            pub mod project_modal;
            pub mod search_modal;
        }
        pub mod overflow_row;
        pub mod toggle;
    }

    pub use sections::footer::Footer;
    pub use sections::header::Header;
    pub use sections::projects::ProjectsSection;

    pub use cards::project_card::{ProjectCard, ProjectCardProperties, from_card_data};

    pub use effects::section_fade::FadeOverlay;

    pub use ui::corner_frame::CornerFrame;
    pub use ui::markdown::MarkdownView;
    pub use ui::modals::profile_modal::ProfileModal;
    pub use ui::modals::project_modal::ProjectModal;
    pub use ui::modals::search_modal::SearchModal;
    pub use ui::overflow_row::OverflowRow;
    pub use ui::toggle::ToggleSlider;
    pub use ui::toggle::ToggleSliderWithSlashLabel;
}

pub mod contexts {
    pub mod accounts;
    pub mod current_user;
    pub mod layout;
    pub mod profile_modal;
    pub mod project_modal;
    pub mod search;

    pub use accounts::AccountsContext;
    pub use current_user::CurrentUserContext;
    pub use layout::LayoutContext;
    pub use profile_modal::ProfileModalContext;
    pub use project_modal::ProjectModalContext;
    pub use search::SearchContext;
}

pub mod data {
    pub mod account;
    pub mod card;
    pub mod fixture;

    pub use account::{AccountData, AccountRole, fetch_accounts};
    pub use card::{CardData, IconUrl, load_cards};
    pub use fixture::CardsFixture;
}

pub mod engines;

pub mod metadata {
    pub mod platforms;
    pub mod tags;

    pub use platforms::{platform_color, platform_label};
    pub use tags::{tag_color, tag_label};
}

pub mod utils;

// i18n module generated by leptos_i18n_build at compile time
include!(concat!(env!("OUT_DIR"), "/i18n/mod.rs"));

pub use app::*;
pub use components::*;
pub use contexts::*;
pub use data::*;
pub use engines::*;
pub use i18n::*;
pub use metadata::*;
pub use utils::*;
