mod app;

// Layout sections
pub mod components {
    pub mod sections {
        pub mod footer;
        pub mod header;
        pub mod projects;
    }

    pub mod cards {
        pub mod project;
    }

    pub mod effects {
        pub mod section_fade;
    }

    pub mod ui {
        pub mod corner_frame;
        pub mod markdown;
        pub mod modals {
            pub mod add_project;
            pub mod login;
            pub mod profile;
            pub mod project;
            pub mod search;
        }
        pub mod overflow_row;
        pub mod toggle;
    }

    pub use sections::footer::Footer;
    pub use sections::header::Header;
    pub use sections::projects::ProjectsSection;

    pub use cards::project::{ProjectCard, ProjectCardProperties, from_project_data};

    pub use effects::section_fade::FadeOverlay;

    pub use ui::corner_frame::CornerFrame;
    pub use ui::markdown::MarkdownView;
    pub use ui::modals::add_project::AddProjectModal;
    pub use ui::modals::login::LoginModal;
    pub use ui::modals::profile::ProfileModal;
    pub use ui::modals::project::ProjectModal;
    pub use ui::modals::search::SearchModal;
    pub use ui::overflow_row::OverflowRow;
    pub use ui::toggle::ToggleSlider;
    pub use ui::toggle::ToggleSliderWithSlashLabel;
}

pub mod contexts {
    pub mod accounts;
    pub mod current_user;
    pub mod layout;
    pub mod modals {
        pub mod add_project;
        pub mod login;
        pub mod profile;
        pub mod project;
        pub mod search;
    }
    pub mod projects;

    pub use accounts::AccountsContext;
    pub use current_user::CurrentUserContext;
    pub use layout::LayoutContext;
    pub use modals::add_project::AddProjectModalContext;
    pub use modals::login::LoginModalContext;
    pub use modals::profile::ProfileModalContext;
    pub use modals::project::ProjectModalContext;
    pub use modals::search::SearchContext;
    pub use projects::ProjectsContext;
}

pub mod data {
    pub mod account;
    pub mod project;

    pub use account::{AccountData, AccountRole, fetch_accounts};
    pub use project::{IconUrl, ProjectData, fetch_projects};
}

pub mod engines;

pub mod metadata {
    pub mod platforms;
    pub mod tags;

    pub use platforms::{platform_color, platform_label};
    pub use tags::{tag_color, tag_label};
}

pub mod utils;

// i18n module generated by leptos_i18n_build at compile time
include!(concat!(env!("OUT_DIR"), "/i18n/mod.rs"));

pub use app::*;
pub use components::*;
pub use contexts::*;
pub use data::*;
pub use engines::*;
pub use i18n::*;
pub use metadata::*;
pub use utils::{api_url, auth_url, login_url, *};
