mod app;

// Layout sections
pub mod components {
    pub mod sections {
        pub mod footer;
        pub mod header;
        pub mod projects;
    }

    pub mod cards {
        pub mod projectcard;
    }

    pub mod effects {
        pub mod sectionfade;
    }

    pub mod ui {
        pub mod cornerframe;
        pub mod datagrid;
    }

    pub use sections::footer::Footer;
    pub use sections::header::Header;
    pub use sections::projects::ProjectsSection;

    pub use cards::projectcard::{ProjectCard, ProjectCardProperties};

    pub use effects::sectionfade::FadeOverlay;

    pub use ui::cornerframe::CornerFrame;
    pub use ui::datagrid::data_grid;
}

pub mod data;

pub mod metadata {
    pub mod platforms;
    pub mod tags;

    pub use platforms::{platform_color, platform_label};
    pub use tags::{tag_color, tag_label};
}

pub mod utils;

// i18n module generated by leptos_i18n_build at compile time
include!(concat!(env!("OUT_DIR"), "/i18n/mod.rs"));

pub use app::*;
pub use components::*;
pub use data::*;
pub use i18n::*;
pub use metadata::*;
pub use utils::*;
